USER_ID=btp-gplmprod
USER_PASS=GoldPLM!@#$%2020

#USER_ID=H366667
#USER_PASS=GoldPLM!@#$%2022

#USER_ID=H504083
#USER_PASS=Goldplm@123

#USER_ID=H527010
#USER_PASS=Goldplm@123

#USER_ID=infodba
#USER_PASS=infodba

#USER_ID=H408649
#USER_PASS=Anjali@1992

#SDEV 4Tier URL
#TC_4T_URL=http://hic024583:8080/tc
#TC_4T_URL=http://sdev.honeywell.com/tc

#GPLMDEV 4Tier URL
#TC_4T_URL=https://gplmdev.honeywell.com/tc
#https://gplmdev.honeywell.com/tc

#GPLMTR 4Tier URL
#TC_4T_URL=https://gplmtr.honeywell.com/tc

#GPLMQA 4Tier URL
#TC_4T_URL=https://gplmqa.honeywell.com/tc

#BFQA 4Tier URL
#TC_4T_URL=http://hic026480.dc.honeywell.com:8080/tc

#Prod 4Tier URL
TC_4T_URL=https://gplm.honeywell.com/tc

#DEV & QA
#ACCOLADE_WS_URL=https://qaccolade.honeywell.com/api/v2/core/projects

#PROD
#ACCOLADE_WS_URL=https://accolade.honeywell.com/api/v2/core/projects

#GPLMDEV : Inbox URL configuration
#AW_INBOX_TASK_URL=https://gplmdev.honeywell.com/awc/#/com.siemens.splm.clientfx.tcui.xrt.showObject?uid=

#GPLMQA : Inbox URL configuration
#AW_INBOX_TASK_URL=https://gplmqa.honeywell.com/awc/#/com.siemens.splm.clientfx.tcui.xrt.showObject?uid=

#PRODUCTION : Inbox URL configuration
#AW_INBOX_TASK_URL=https://gplm.honeywell.com/awc/#/com.siemens.splm.clientfx.tcui.xrt.showObject?uid=

#Mail Configuration

MAIL_FROM=goldplmsupport@honeywell.com
MAIL_HOST=smtp.honeywell.com
MAIL_SUBJECT=Your Attention/Action Needed: Certifications and Regulatory Updates
MAIL_FOOTER_CONTENT=</br></br>This e-mail, and any attachments thereto, are intended only for use by the addressee(s) named herein and contain Honeywell confidential information. If you are not the intended recipient of this e-mail, you are hereby notified that any dissemination, distribution or copying which amounts to misappropriation of this e-mail and any attachments thereto, is strictly prohibited. If you have received this e-mail in error, please immediately notify GOLD PLM Team and permanently delete the original and any copy of any e-mail and any printout thereof
LDAP_URL=http://gplmuam.honeywell.com:8003/api/v1/ldap?eid=


